import xmlFormat from 'xml-formatter';

export class ShipmentBaseTag {
    public static ShipmentHeader: string = xmlFormat(`<ShipmentHeader><ShipmentGid><Gid><DomainName>EMBDEV</DomainName><Xid>EMBARQUE1</Xid></Gid></ShipmentGid><ShipmentRefnum><ShipmentRefnumQualifierGid><Gid><DomainName>EMBDEV</DomainName><Xid>CLL_IMPOSTO_SOMADO</Xid></Gid></ShipmentRefnumQualifierGid><ShipmentRefnumValue>S</ShipmentRefnumValue></ShipmentRefnum><ShipmentRefnum><ShipmentRefnumQualifierGid><Gid><DomainName>EMBDEV</DomainName><Xid>CLL_IMPOSTO_INCLUSO</Xid></Gid></ShipmentRefnumQualifierGid><ShipmentRefnumValue>S</ShipmentRefnumValue></ShipmentRefnum><InternalShipmentStatus><StatusTypeGid><Gid><DomainName>EMBDEV</DomainName><Xid>CLL_STATUS_VIAGEM</Xid></Gid></StatusTypeGid><StatusValueGid><Gid><DomainName>EMBDEV</DomainName><Xid>PLANEJADO</Xid></Gid></StatusValueGid></InternalShipmentStatus><InternalShipmentStatus><StatusTypeGid><Gid><DomainName>EMBDEV</DomainName><Xid>CLL_STATUS_EMISSAO</Xid></Gid></StatusTypeGid><StatusValueGid><Gid><DomainName>EMBDEV</DomainName><Xid>PRE_EMISSAO_ENVIADA</Xid></Gid></StatusValueGid></InternalShipmentStatus><ServiceProviderGid><Gid><DomainName>EMBDEV</DomainName><Xid>CAR-12521</Xid></Gid></ServiceProviderGid><TotalPlannedCost><FinancialAmount><GlobalCurrencyCode>BRL</GlobalCurrencyCode><MonetaryAmount>100.00</MonetaryAmount></FinancialAmount></TotalPlannedCost><TotalActualCost><FinancialAmount><GlobalCurrencyCode>BRL</GlobalCurrencyCode><MonetaryAmount>100.00</MonetaryAmount></FinancialAmount></TotalActualCost><TotalWeightedCost><FinancialAmount><GlobalCurrencyCode>BRL</GlobalCurrencyCode><MonetaryAmount>100.00</MonetaryAmount></FinancialAmount></TotalWeightedCost><ShipmentCost><ShipmentCostSeqno>1</ShipmentCostSeqno><CostType>B</CostType><Cost><FinancialAmount><GlobalCurrencyCode>BRL</GlobalCurrencyCode><MonetaryAmount>100.00</MonetaryAmount></FinancialAmount></Cost></ShipmentCost><TransportModeGid><Gid><Xid>TL</Xid></Gid></TransportModeGid><InvolvedParty><InvolvedPartyQualifierGid><Gid><DomainName>EMBDEV</DomainName><Xid>CLL_TOMADOR</Xid></Gid></InvolvedPartyQualifierGid><InvolvedPartyLocationRef><LocationRef><LocationGid><Gid><DomainName>EMBDEV</DomainName><Xid>ORG-8027-30018</Xid></Gid></LocationGid></LocationRef></InvolvedPartyLocationRef></InvolvedParty></ShipmentHeader>`,
        { collapseContent: true }
    );

    public static ShipmentHeader2: string = xmlFormat(`<ShipmentHeader2><Perspective>B</Perspective></ShipmentHeader2>`,
        { collapseContent: true }
    );

    public static ShipmentStop: string = xmlFormat(`<Stops><ShipmentStop><StopSequence>1</StopSequence><LocationRef><LocationGid><Gid><DomainName>EMBDEV</DomainName><Xid>76515</Xid></Gid></LocationGid></LocationRef><StopType>P</StopType></ShipmentStop><ShipmentStop><StopSequence>2</StopSequence><LocationRef><LocationGid><Gid><DomainName>IPIRANGA</DomainName><Xid>ORG-8027-30018</Xid></Gid></LocationGid></LocationRef><StopType>D</StopType></ShipmentStop></Stops>`,
        { collapseContent: true }
    ).replace(`<Stops>`, '').replace(`</Stops>`, '');

}